### ISSUE TITLE
Azure Server 

### ISSUE THREAD

**Issue by kmbisset89** [hkarthik7/azure-devops-java-sdk#67] opened 2023-08-18 13:13 UTC
Issue:
The library provides functionality to connect to Azure DevOps services and interact with them using a provided API. However, it seems that there is an issue when attempting to connect to Azure DevOps Server instances using the library's latest version.

Steps to Reproduce:

Create an instance of the library.
Set the base instance URL to the Azure DevOps Server instance: Instance.BASE_INSTANCE.instance = "https://devops.jtaps.us"
Initialize the API using the new method: val webApi = AzDClientApi("JTAPS", pat)
Expected Behavior:
The library should successfully connect to the Azure DevOps Server instance using the provided organization name (collection name in this context) and personal access token (PAT).

Actual Behavior:
When using the new method and providing the organization name (collection name) as 'JTAPS', the following exception is thrown: InvalidOrganizationNameException: Couldn't find the organization name 'JTAPS' in instance 'https://devops.jtaps.us/'.

Additional Information:
It appears that the library's behavior aligns with the naming paradigm used by Azure DevOps services, but it does not accommodate the naming convention used by Azure DevOps Server instances. Azure DevOps Server seems to use a different naming paradigm for organizations (collections) that does not match the organization name provided when initializing the library.

**Comment by kmbisset89** [comment] 2023-08-18 13:24
On further debugging. I went to the stacktrace of where that was being thrown and got this :

﻿{"$id":"1","innerException":null,"message":"TF400813: Resource not available for anonymous access. Client authentication required.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
﻿
﻿I am unsure of what all of this mean, but I did give a valid fresh all access PAT to the Client.

**Comment by hkarthik7** [comment] 2023-08-18 13:48
Hiya @kmbisset89, Could you please give it a try as below?

```java
Instance.BASE_INSTANCE.setInstance("https://devops.jtaps.us/");

var webApi = new AzDClientApi(organisation, personalAccessToken);

var core = webApi.getCoreApi();
core.getProjects();

```

**Comment by kmbisset89** [comment] 2023-08-18 13:57
Instance.BASE_INSTANCE.instance = "https://devops.jtaps.us/"
        val webApi = AzDClientApi("JTAPS", pat)

        val core = webApi.coreApi
        try {
            // get the list of projects
            core.projects
            
            
This is what I tried and got the same error. I am wondering if it has to do with the Basic Authorization method that is needed.

**Comment by hkarthik7** [comment] 2023-08-21 08:50
Hiya @kmbisset89, Instead of setting the URL as a first instance, could you please try to pass the entire URL and call [RestClient.send](https://hkarthik7.github.io/azd-docs/org/azd/utils/RestClient.html) and give it a try?

The issue you're facing is because of [getLocationUrl](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/utils/RestClientProvider.java#L27) which is trying to retrieve the location url for given resource id and base instance. This is the limitation we're currently having in the library and I'm working on adding this feature which will be released in v6.x.

I'm sorry that you're facing this limitation, please refer [this](https://azure-devops-java-sdk-docs.readthedocs.io/en/latest/docs/tutorial/) to call Azure DevOps Rest API.

**Comment by hkarthik7** [comment] 2023-09-21 05:47
Hiya @kmbisset89, did you get a chance to give the above a try? Is it working?

**Comment by hkarthik7** [comment] 2023-10-26 06:58
Hiya @kmbisset89, I'm closing this for now, please re-open this if the issue is not solved.

**Closed by hkarthik7** 2023-10-26 06:58 UTC
